services:
  app:
    image: silenloc/fig
    container_name: fig
    user: "root"
    environment:
      PROJECT_ROOT: "/srv/git"
      API_KEY: "secure"
      DB_PATH: "/data/fig.db"
    ports:
      - "8080:80"
    volumes:
      - git_backend:/srv/git
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  git_backend:
