services:
  app:
    image: silenloc/fig
    container_name: fig
    environment:
      PROJECT_ROOT: "tests/git/srv"
    ports:
      - "8080:80"
    volumes:
      - git_backend:/srv/git
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  git_backend:
